@startuml

hide members
class document  <<(M, #00ffbb)Model>> {

}
class student <<(M, #00ffbb)Model>> { 

}
class professor <<(M, #00ffbb)Model>> {

}
class group <<(M, #00ffbb)Model>> {

}
class item <<(M, #00ffbb)Model>> {

}
class documentController <<(C, #00bfff)Controller>> {

}
class studentController <<(C, #00bfff)Controller>> {

}
class professorController <<(C, #00bfff)Controller>> {

}
class professorRoute <<(R, #ff0040)Route>> {

}
class studentRoute <<(R, #ff0040)Route>> {

}
class documentRoute  <<(R, #ff0040)Route>> {

}
class groupController <<(C, #00bfff) Controller>> {

}
class groupRouter <<(R, #ff0040)Route>> {

}
class department <<(M, #00ffbb)Model>> {

}
class departmentController <<(C, #00bfff) Controller>> {

}
class departmentRoute <<(R, #ff0040)Route>> {

}
Document "1" --- "0..*" group
group o-- item: have >
documentController <.. Document

student ..> studentController
professor ..> professorController
student "0..*" -- "1" Document

documentController ..> documentRoute
studentController ..> studentRoute
professorController ..> professorRoute
groupController <.. group
groupController ..> groupRouter

@enduml