language: node_js
node_js: 8.15.1
services:
  - docker
  - mongodb
env:
  - SECRET=othersecret
cache:
  directories:
    - "node_modules"

before_script:
  - npm update -q
  - cd backend
  - npm install

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: npm run test:unit
    - script: npm run test:integration
      name: "Integration Tests"
    - before_script: 
      - cd .. 
      - ls remote
      # - cd complementaries-activities
    #- script: npm test
      name: "Test in frontend"
    #- stage: deploy
    #  name: "Deploy to heroku"
    #  script: 