language: node_js
node_js: 8.15.1
services:
  - docker
  - mongodb
cache:
  directories:
    - "node_modules"

before_script:
  - npm update -q
  - cd backend
  - npm install
script: 
  - npm run test:unit

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: npm run test:unit
    - script: npm run test:integration
      name: "Integration Tests"
    #- stage: deploy
    #  name: "Deploy to heroku"
    #  script: 