language: node_js
node_js: 8.15.1
services:
  - docker

stages:
  - test
  - package



before_script:
  - npm update -q
  - cd backend
  - npm install

test:
  stage: test
  script: 
    - npm run test:unit

package:
  stage: package
  cache:
    directories:
      - "node_modules"