language: node_js
node_js:
  - "stable"

cache:
  directories:
    - "node_modules"
script:
  - cd backend
  - npm install
  - npm run test:unit
#stages:
 # - test
  #- package
  #- deploy

#before_script:
 # - whoami

#test site:
 # stage: test
  #script: 
   # - cd backend
    #- npm install && npm run test:unit