language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
image: node
stages:
  - test
  - package
  - deploy

before_script:
  - whoami
  - pwd

test site:
  stage: test
  script: 
    - cd backend
    - npm install && npm run test:integration