language: node_js
node_js:
  - "stable"
services:
  - docker
cache:
  directories:
    - "node_modules"

before_script:
  - docker pull node
  - cd backend
  - npm install
script: 
  - npm run test:unit