language: node_js
node_js:
  - "stable"
env:
  global:
    - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - "node_modules"

before_script:
  - cd backend
  - npm install
script: 
  - npm run test:unit